/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 coffee_for_two.glb -T 
Files: coffee_for_two.glb [14.65MB] > /Users/dileepkumarsharma/Desktop/Portfolio/3D Portfolio/public/models/coffee_for_two-transformed.glb [863.99KB] (94%)
Author: Elen (https://sketchfab.com/Kitty999)
License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
Source: https://sketchfab.com/3d-models/coffee-for-two-018f683e86ea42eb8e98935e890eb9fd
Title: Coffee for two
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Coffee(props) {
  const { nodes, materials } = useGLTF(
    "/models/coffee_for_two-transformed.glb"
  );
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_5.geometry}
        material={materials.Coffee}
        position={[0.246, 0.376, -0.285]}
      />
      <mesh
        geometry={nodes.Object_7.geometry}
        material={materials.Cup_and_Plate}
        position={[0.241, 0.039, -0.323]}
      />
      <mesh
        geometry={nodes.Object_9.geometry}
        material={materials.Serviette}
        position={[0.243, 0.028, -0.263]}
      />
      <mesh
        geometry={nodes.Object_11.geometry}
        material={materials.Spoon}
        position={[-0.072, 0.06, 0.683]}
        rotation={[0, 0, -0.018]}
      />
    </group>
  );
}

useGLTF.preload("/models/coffee_for_two-transformed.glb");
