/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 computer.glb -T 
Files: computer.glb [540.4KB] > /Users/dileepkumarsharma/Desktop/Portfolio/3D Portfolio/public/models/computer-transformed.glb [114.08KB] (79%)
Author: assetfactory (https://sketchfab.com/assetfactory)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/sci-fi-computer-game-ready-53e7eeb0f69540d2892ad6aa5f47bd39
Title: Sci - fi computer game ready
*/

import { useGLTF } from "@react-three/drei";

export default function Computer(props) {
  const { nodes, materials } = useGLTF("/models/computer-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane002_digital_displays_0.geometry}
        material={materials.digital_displays}
        position={[0, 0.289, 3.122]}
        rotation={[-1.469, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane002_digital_display_sides_0.geometry}
        material={materials.digital_display_sides}
        position={[0, 0.289, 3.122]}
        rotation={[-1.469, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle_metal_2_0.geometry}
        material={materials.metal_2}
        position={[0, 0, -0.948]}
        rotation={[0, Math.PI / 2, 0]}
        scale={1.238}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle_metal_1_0.geometry}
        material={materials.metal_1}
        position={[0, 0, -0.948]}
        rotation={[0, Math.PI / 2, 0]}
        scale={1.238}
      />
    </group>
  );
}

useGLTF.preload("/models/computer-transformed.glb");
